[build]
  command = "npm start"  # Assuming this is the command to start your app in production
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.17.0"
